name: SonarCloud

on:
  workflow_run:
    workflows: ["Tests (PHP)"]
    types: [completed]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    outputs:
      alert_status: ${{ steps.sonarqube-report.outputs.alert_status }}
      bugs: ${{ steps.sonarqube-report.outputs.bugs }}
      code_smells: ${{ steps.sonarqube-report.outputs.code_smells }}
      coverage: ${{ steps.sonarqube-report.outputs.coverage }}
      duplicated_lines_density: ${{ steps.sonarqube-report.outputs.duplicated_lines_density }}
      ncloc: ${{ steps.sonarqube-report.outputs.ncloc }}
      reliability_rating: ${{ steps.sonarqube-report.outputs.reliability_rating }}
      security_rating: ${{ steps.sonarqube-report.outputs.security_rating }}
      sqale_index: ${{ steps.sonarqube-report.outputs.sqale_index }}
      sqale_rating: ${{ steps.sonarqube-report.outputs.sqale_rating }}
      vulnerabilities: ${{ steps.sonarqube-report.outputs.vulnerabilities }}
      git_ref: ${{ steps.sonarqube-report.outputs.git_ref }}

    permissions:
      actions: read
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Download test artifacts
        continue-on-error: true
        uses: actions/download-artifact@v5
        with:
          name: test-results
          path: ./coverage
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarQube Scan
        id: sonarqube-scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Fail job if Quality Gate fails (SonarCloud)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          SONAR_PROJECT_KEY=$(grep '^sonar.projectKey=' sonar-project.properties | cut -d= -f2)

          if [ "${{ github.event.workflow_run.pull_requests[0].number }}" != "" ]; then
            REF="pullRequest=${{ github.event.workflow_run.pull_requests[0].number }}"
          else
            ENCODED_REF=$(echo "${{ github.event.workflow_run.head_branch }}" | jq -sRr @uri)
            REF="branch=$ENCODED_REF"
          fi

          STATUS=$(curl --silent \
            -H "Authorization: Bearer $SONAR_TOKEN" \
            "https://sonarcloud.io/api/measures/component?metricKeys=alert_status&component=$SONAR_PROJECT_KEY&$REF" \
            | jq -r '.component.measures[0].value')

          echo "Quality Gate: ${STATUS}"
          [ "$STATUS" = "OK" ] || { echo "Quality Gate failed"; exit 1; }

      - name: Output SonarQube Quality Gate Status
        id: sonarqube-report
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          SONAR_PROJECT_KEY=$(grep '^sonar.projectKey=' sonar-project.properties | cut -d= -f2)

          echo Finding branch or pull request number...
          if [ "${{ github.event.number }}" != "" ]; then
            REF="pullRequest=${{ github.event.number }}"
          else
            ENCODED_REF=$(echo "${{ github.ref_name }}" | jq -sRr @uri)
            REF="branch=$ENCODED_REF"
          fi

          echo "Fetching..."
          DATA=$(curl --silent --request GET  --url "https://sonarcloud.io/api/measures/component?metricKeys=alert_status%2Cbugs%2Ccode_smells%2Ccoverage%2Cduplicated_lines_density%2Cncloc%2Creliability_rating%2Csecurity_rating%2Csqale_index%2Csqale_rating%2Cvulnerabilities&component=$SONAR_PROJECT_KEY&$REF" --header "Authorization: Bearer $SONAR_TOKEN")

          echo "extracting data..."
          alert_status=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "alert_status") | .value')
          bugs=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "bugs") | .value')
          code_smells=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "code_smells") | .value')
          coverage=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "coverage") | .value')
          duplicated_lines_density=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "duplicated_lines_density") | .value')
          ncloc=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "ncloc") | .value')
          reliability_rating=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "reliability_rating") | .value')
          security_rating=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "security_rating") | .value')
          sqale_index=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "sqale_index") | .value')
          sqale_rating=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "sqale_rating") | .value')
          vulnerabilities=$(echo "$DATA" | jq -r '.component.measures[] | select(.metric == "vulnerabilities") | .value')

          echo "alert_status=${alert_status}" >> "$GITHUB_OUTPUT"
          echo "bugs=${bugs}" >> "$GITHUB_OUTPUT"
          echo "code_smells=${code_smells}" >> "$GITHUB_OUTPUT"
          echo "coverage=${coverage}" >> "$GITHUB_OUTPUT"
          echo "duplicated_lines_density=${duplicated_lines_density}" >> "$GITHUB_OUTPUT"
          echo "ncloc=${ncloc}" >> "$GITHUB_OUTPUT"
          echo "reliability_rating=${reliability_rating}" >> "$GITHUB_OUTPUT"
          echo "security_rating=${security_rating}" >> "$GITHUB_OUTPUT"
          echo "sqale_index=${sqale_index}" >> "$GITHUB_OUTPUT"
          echo "sqale_rating=${sqale_rating}" >> "$GITHUB_OUTPUT"
          echo "vulnerabilities=${vulnerabilities}" >> "$GITHUB_OUTPUT"
          echo "git_ref=${REF}" >> "$GITHUB_OUTPUT"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        if: github.event_name == 'pull_request'
        with:
          message: |
            ## SonarCloud Analysis Results
            ### Quality Gate Status: ${{ steps.sonarqube-report.outputs.alert_status }}
            ### Metrics
            - **Bugs**: ${{ steps.sonarqube-report.outputs.bugs }}
            - **Code Smells**: ${{ steps.sonarqube-report.outputs.code_smells }}
            - **Coverage**: ${{ steps.sonarqube-report.outputs.coverage }}
            - **Duplicated Lines Density**: ${{ steps.sonarqube-report.outputs.duplicated_lines_density }}
            - **Lines of Code (ncloc)**: ${{ steps.sonarqube-report.outputs.ncloc }}
            - **Reliability Rating**: ${{ steps.sonarqube-report.outputs.reliability_rating }}
            - **Security Rating**: ${{ steps.sonarqube-report.outputs.security_rating }}
            - **Technical Debt (sqale index)**: ${{ steps.sonarqube-report.outputs.sqale_index }}
            - **Maintainability Rating**: ${{ steps.sonarqube-report.outputs.sqale_rating }}
            - **Vulnerabilities**: ${{ steps.sonarqube-report.outputs.vulnerabilities }}
            ### More details
            - [SonarCloud dashboard](https://sonarcloud.io/dashboard?id=catch-design_catch-oss-tmhoauth&${{ steps.sonarqube-report.outputs.git_ref }})
            - [View the full report](https://sonarcloud.io/project/issues?id=catch-design_catch-oss-tmhoauth&${{ steps.sonarqube-report.outputs.git_ref }}&resolved=false)
            - [View the Quality Gate](https://sonarcloud.io/summary/new_code?id=catch-design_catch-oss-tmhoauth&${{ steps.sonarqube-report.outputs.git_ref }})
